// <auto-generated />
using System;
using DotVida.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotVida.Infra.Data.Migrations
{
    [DbContext(typeof(DotVidaDbContext))]
    partial class DotVidaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DotVida.Domain.Entities.Attendance", b =>
                {
                    b.Property<Guid>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommentsDoctor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Height")
                        .HasPrecision(1, 2)
                        .HasColumnType("decimal(1,2)");

                    b.Property<Guid?>("PatientEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Weight")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.HasKey("AttendanceId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientEntryId");

                    b.HasIndex("PatientId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("DotVida.Domain.Entities.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("BloodType")
                        .HasColumnType("int");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmployeeStatus")
                        .HasColumnType("bit");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PersonStatus")
                        .HasColumnType("bit");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("Specialty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("DotVida.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("BloodType")
                        .HasColumnType("int");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("PersonStatus")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("DotVida.Domain.Entities.PatientEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateEntry")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateExit")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusEntry")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PatientsEntry");
                });

            modelBuilder.Entity("DotVida.Domain.Entities.Personal_Illness", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AttendanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SickId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StatusSick")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceId");

                    b.HasIndex("PatientId");

                    b.HasIndex("SickId");

                    b.ToTable("Personal_Illnesses");
                });

            modelBuilder.Entity("DotVida.Domain.Entities.Sick", b =>
                {
                    b.Property<Guid>("SickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("SickId");

                    b.ToTable("Sicks");
                });

            modelBuilder.Entity("DotVida.Domain.Entities.Attendance", b =>
                {
                    b.HasOne("DotVida.Domain.Entities.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotVida.Domain.Entities.PatientEntry", null)
                        .WithMany("Attendance")
                        .HasForeignKey("PatientEntryId");

                    b.HasOne("DotVida.Domain.Entities.Patient", null)
                        .WithMany("Attendances")
                        .HasForeignKey("PatientId");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("DotVida.Domain.Entities.Personal_Illness", b =>
                {
                    b.HasOne("DotVida.Domain.Entities.Attendance", null)
                        .WithMany("Sick")
                        .HasForeignKey("AttendanceId");

                    b.HasOne("DotVida.Domain.Entities.Patient", null)
                        .WithMany("Sick")
                        .HasForeignKey("PatientId");

                    b.HasOne("DotVida.Domain.Entities.Sick", "Sick")
                        .WithMany()
                        .HasForeignKey("SickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sick");
                });

            modelBuilder.Entity("DotVida.Domain.Entities.Attendance", b =>
                {
                    b.Navigation("Sick");
                });

            modelBuilder.Entity("DotVida.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Sick");
                });

            modelBuilder.Entity("DotVida.Domain.Entities.PatientEntry", b =>
                {
                    b.Navigation("Attendance");
                });
#pragma warning restore 612, 618
        }
    }
}
